# Generated by Django 5.1.1 on 2025-01-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('can_issue_books', 'Can issue books'), ('can_return_books', 'Can return books'), ('can_view_books_members', 'Can view books and members')]},
        ),
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
