# Generated by Django 5.1.1 on 2025-01-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_staff_options_book_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('lost', 'Lost')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(default=1000, max_length=50),
            preserve_default=False,
        ),
    ]
