# Generated by Django 5.1.1 on 2025-01-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_status_transaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
    ]
